vers.versionName=26.1.2
vers.mcVersion=26.1.2
vers.mcVersionRange=[26.1.1,26.1.2]
vers.supportedMcVersions=26.1.1,26.1.2

vers.deps.fml=26.1.2.78
vers.deps.yacl=3.9.5+26.1-neoforge
vers.deps.klf=3.1

vers.deps.compat.rightClickHarvest=33nxkOzf
vers.deps.compat.veinminer=7GhgEsTA
vers.deps.compat.fallingTree=YpsBfAWL
vers.deps.compat.kleeSlabs=qy3qkejn
vers.deps.compat.balm=FAvYxD39
vers.deps.compat.treeHarvester=PIkMhpKe
vers.deps.compat.collective=iXqgYZEw

modstitch.platform=moddevgradle
