vers.versionName=26.1.2
vers.mcVersion=26.1.2
vers.mcVersionRange=>=26.1.1 <=26.1.2
vers.supportedMcVersions=26.1.1,26.1.2

vers.deps.fapi=0.154.2+26.1.2
vers.deps.yacl=3.9.5+26.1-fabric
vers.deps.modMenu=18.0.0

vers.deps.compat.rightClickHarvest=spaSLGmu
vers.deps.compat.veinminer=h4Z7xAL0
vers.deps.compat.fallingTree=YpsBfAWL
vers.deps.compat.kleeSlabs=E0bAQxK1
vers.deps.compat.balm=u130G6gO
vers.deps.compat.treeHarvester=PIkMhpKe
vers.deps.compat.collective=iXqgYZEw

modstitch.platform=fabric-loom
