vers.versionName=1.21.11
vers.mcVersion=1.21.11
vers.mcVersionRange=[1.21.11]
vers.supportedMcVersions=1.21.11

vers.deps.fml=21.11.44
vers.deps.yacl=3.8.1+1.21.11-neoforge
vers.deps.klf=3.1

vers.deps.compat.rightClickHarvest=8SnX8Vj7
vers.deps.compat.veinminer=BY3LQfSE
vers.deps.compat.fallingTree=Hnj3s9Ez
vers.deps.compat.kleeSlabs=PI5CnL0i
vers.deps.compat.balm=tKWaiIeW
vers.deps.compat.treeHarvester=8mfyGsIg
vers.deps.compat.collective=e4SDY5SX

modstitch.platform=moddevgradle
