vers.versionName=1.21.11
vers.mcVersion=1.21.11
vers.mcVersionRange=>1.21.10
vers.supportedMcVersions=1.21.11

vers.deps.fapi=0.141.6+1.21.11
vers.deps.yacl=3.8.1+1.21.11-fabric
vers.deps.modMenu=17.0.1-beta.1

vers.deps.compat.rightClickHarvest=MJkjKHul
vers.deps.compat.veinminer=7c3RO0Qs
vers.deps.compat.fallingTree=Hnj3s9Ez
vers.deps.compat.kleeSlabs=LArQWMkb
vers.deps.compat.balm=5POKgjJn
vers.deps.compat.treeHarvester=8mfyGsIg
vers.deps.compat.collective=e4SDY5SX

modstitch.platform=fabric-loom-remap
