vers.versionName=26.2
vers.mcVersion=26.2
vers.mcVersionRange=[26.2]
vers.supportedMcVersions=26.2

vers.deps.fml=26.2.0.10-beta
vers.deps.yacl=3.9.5+26.2-neoforge
vers.deps.klf=3.1

vers.deps.compat.rightClickHarvest=bl9vxSD9
vers.deps.compat.veinminer=n6eLxGdD
vers.deps.compat.fallingTree=sOoH5kkd
vers.deps.compat.kleeSlabs=2QlPdVwy
vers.deps.compat.balm=joHDpNpK
vers.deps.compat.treeHarvester=3VcDfhZP
vers.deps.compat.collective=M75JwjyS

modstitch.platform=moddevgradle
